services:
  nginx_webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - web_data:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - php_app

  php_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - web_data:/var/www/html
    ports:
      - 9000:9000
    env_file:
      - .env

  db:
    image: mysql:latest
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./src/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    env_file:
      - .env

volumes:
  web_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src/php
